-- Gerado por tools/loja.py a partir do items.xml e das lojas de NPC do Canary 3.6.1 (nao editar a mao).
IdleShopData = {
	{ id = 3264, name = "sword", kind = "arma", wtype = "sword", voc = "K", level = 1, price = 307, attack = 14, defense = 12, extradef = 1 },
	{ id = 3276, name = "hatchet", kind = "arma", wtype = "axe", voc = "K", level = 1, price = 307, attack = 15, defense = 8 },
	{ id = 7773, name = "steel axe", kind = "arma", wtype = "axe", voc = "K", level = 1, price = 307, attack = 21, defense = 10 },
	{ id = 3327, name = "daramian mace", kind = "arma", wtype = "club", voc = "K", level = 1, price = 330, attack = 21, defense = 12 },
	{ id = 660, name = "fiery spike sword", kind = "arma", wtype = "sword", voc = "K", level = 1, price = 307, attack = 20, defense = 21, extradef = 2 },
	{ id = 679, name = "icy spike sword", kind = "arma", wtype = "sword", voc = "K", level = 1, price = 307, attack = 20, defense = 21, extradef = 2 },
	{ id = 3277, name = "spear", kind = "arma", wtype = "distance", voc = "P", level = 12, price = 9, attack = 25, range = 3, stack = true },
	{ id = 3298, name = "throwing knife", kind = "arma", wtype = "distance", voc = "P", level = 12, price = 25, attack = 25, range = 4, stack = true },
	{ id = 3348, name = "banana staff", kind = "arma", wtype = "club", voc = "K", level = 20, price = 3180, attack = 25, defense = 15, extradef = 2 },
	{ id = 7366, name = "viper star", kind = "arma", wtype = "distance", voc = "P", level = 24, price = 9, attack = 28, range = 4, stack = true },
	{ id = 3346, name = "ripper lance", kind = "arma", wtype = "axe", voc = "K", level = 24, price = 4447, attack = 28, defense = 7, two = true },
	{ id = 3287, name = "throwing star", kind = "arma", wtype = "distance", voc = "P", level = 32, price = 42, attack = 30, range = 4, stack = true },
	{ id = 3265, name = "two handed sword", kind = "arma", wtype = "sword", voc = "K", level = 32, price = 7672, attack = 30, defense = 25, two = true },
	{ id = 7381, name = "mammoth whopper", kind = "arma", wtype = "club", voc = "K", level = 32, price = 7672, attack = 30, defense = 15 },
	{ id = 3347, name = "hunting spear", kind = "arma", wtype = "distance", voc = "P", level = 40, price = 75, attack = 32, range = 3, stack = true },
	{ id = 7378, name = "royal spear", kind = "arma", wtype = "distance", voc = "P", level = 52, price = 15, attack = 35, range = 3, stack = true },
	{ id = 661, name = "fiery relic sword", kind = "arma", wtype = "sword", voc = "K", level = 52, price = 19768, attack = 34, defense = 24, extradef = 1 },
	{ id = 663, name = "fiery blacksteel sword", kind = "arma", wtype = "sword", voc = "K", level = 52, price = 19768, attack = 35, defense = 22 },
	{ id = 7367, name = "enchanted spear", kind = "arma", wtype = "distance", voc = "P", level = 64, price = 19, attack = 38, range = 4, stack = true },
	{ id = 9378, name = "musician's bow", kind = "arma", wtype = "distance", voc = "P", level = 64, price = 29791, range = 4, ammo = "arrow", two = true },
	{ id = 662, name = "fiery mystic blade", kind = "arma", wtype = "sword", voc = "K", level = 64, price = 29791, attack = 36, defense = 25, extradef = 2 },
	{ id = 681, name = "icy mystic blade", kind = "arma", wtype = "sword", voc = "K", level = 64, price = 29791, attack = 36, defense = 25, extradef = 2 },
	{ id = 12733, name = "shimmer bow", kind = "arma", wtype = "distance", voc = "P", level = 84, price = 51103, attack = 1, range = 6, ammo = "arrow", two = true },
	{ id = 19356, name = "triple bolt crossbow", kind = "arma", wtype = "distance", voc = "P", level = 84, price = 51103, attack = 3, range = 5, ammo = "bolt", two = true },
	{ id = 3312, name = "silver mace", kind = "arma", wtype = "club", voc = "K", level = 84, price = 51103, attack = 41, defense = 30, extradef = 2 },
	{ id = 7386, name = "mercenary sword", kind = "arma", wtype = "sword", voc = "K", level = 84, price = 51103, attack = 43, defense = 27, two = true },
	{ id = 20082, name = "crude umbral bow", kind = "arma", wtype = "distance", voc = "P", level = 96, price = 66655, attack = 2, range = 7, ammo = "arrow", two = true },
	{ id = 16163, name = "crystal crossbow", kind = "arma", wtype = "distance", voc = "P", level = 96, price = 105000, attack = 4, range = 6, ammo = "bolt", two = true },
	{ id = 3281, name = "giant sword", kind = "arma", wtype = "sword", voc = "K", level = 96, price = 66655, attack = 46, defense = 22, two = true },
	{ id = 3315, name = "guardian halberd", kind = "arma", wtype = "axe", voc = "K", level = 96, price = 66655, attack = 46, defense = 15, two = true },
	{ id = 3288, name = "magic sword", kind = "arma", wtype = "sword", voc = "K", level = 116, price = 97183, attack = 48, defense = 35, extradef = 3 },
	{ id = 7423, name = "skullcrusher", kind = "arma", wtype = "club", voc = "K", level = 116, price = 97183, attack = 51, defense = 20, two = true },
	{ id = 14768, name = "thorn spitter", kind = "arma", wtype = "distance", voc = "P", level = 150, price = 162300, attack = 9, range = 6, ammo = "bolt", two = true },
	{ id = 34089, name = "soulpiercer", kind = "arma", wtype = "distance", voc = "P", level = 400, price = 1152300, attack = 9, range = 6, ammo = "bolt", two = true },
	{ id = 16161, name = "crystalline axe", kind = "arma", wtype = "axe", voc = "K", level = 128, price = 118264, attack = 51, defense = 29, extradef = 3 },
	{ id = 49522, name = "inferniarch arbalest", kind = "arma", wtype = "distance", voc = "P", level = 300, price = 648300, attack = 8, range = 8, ammo = "bolt", two = true },
	{ id = 8097, name = "solar axe", kind = "arma", wtype = "axe", voc = "K", level = 132, price = 125752, attack = 52, defense = 29, extradef = 3 },
	{ id = 8024, name = "devileye", kind = "arma", wtype = "distance", voc = "P", level = 160, price = 184620, attack = 20, range = 6, ammo = "bolt", two = true },
	{ id = 7368, name = "assassin star", kind = "arma", wtype = "distance", voc = "P", level = 172, price = 100, attack = 65, range = 4, stack = true },
	{ id = 3402, name = "native armor", kind = "armadura", wtype = "armor", voc = "SDPK", level = 1, price = 306, armor = 7 },
	{ id = 8064, name = "ethno coat", kind = "armadura", wtype = "armor", voc = "DS", level = 1, price = 750, armor = 7 },
	{ id = 3571, name = "ranger's cloak", kind = "armadura", wtype = "armor", voc = "P", level = 1, price = 550, armor = 7 },
	{ id = 3359, name = "brass armor", kind = "armadura", wtype = "armor", voc = "SDPK", level = 9, price = 786, armor = 8 },
	{ id = 3357, name = "plate armor", kind = "armadura", wtype = "armor", voc = "SDPK", level = 27, price = 4674, armor = 10 },
	{ id = 3383, name = "dark armor", kind = "armadura", wtype = "armor", voc = "SDPK", level = 27, price = 4674, armor = 10 },
	{ id = 3380, name = "noble armor", kind = "armadura", wtype = "armor", voc = "SDPK", level = 36, price = 8076, armor = 11 },
	{ id = 19358, name = "albino plate", kind = "armadura", wtype = "armor", voc = "SDPK", level = 36, price = 8076, armor = 11 },
	{ id = 3360, name = "golden armor", kind = "armadura", wtype = "armor", voc = "KP", level = 63, price = 60000, armor = 14 },
	{ id = 8061, name = "skullcracker armor", kind = "armadura", wtype = "armor", voc = "K", level = 85, price = 54000, armor = 14 },
	{ id = 3386, name = "dragon scale mail", kind = "armadura", wtype = "armor", voc = "KP", level = 72, price = 120000, armor = 15 },
	{ id = 3388, name = "demon armor", kind = "armadura", wtype = "armor", voc = "SDPK", level = 81, price = 39666, armor = 16 },
	{ id = 37608, name = "green demon armor", kind = "armadura", wtype = "armor", voc = "SDPK", level = 81, price = 39666, armor = 16 },
	{ id = 22530, name = "firesoul tabard", kind = "armadura", wtype = "armor", voc = "P", level = 200, price = 240300, armor = 18 },
	{ id = 22531, name = "earthsoul tabard", kind = "armadura", wtype = "armor", voc = "P", level = 200, price = 240300, armor = 18 },
	{ id = 22518, name = "Fireheart cuirass", kind = "armadura", wtype = "armor", voc = "K", level = 200, price = 240300, armor = 18 },
	{ id = 22519, name = "fireheart hauberk", kind = "armadura", wtype = "armor", voc = "K", level = 200, price = 240300, armor = 18 },
	{ id = 39147, name = "spiritthorn armor", kind = "armadura", wtype = "armor", voc = "K", level = 400, price = 960300, armor = 20 },
	{ id = 51262, name = "norcferatu tuskplate", kind = "armadura", wtype = "armor", voc = "K", level = 270, price = 437700, armor = 22 },
	{ id = 3552, name = "leather boots", kind = "botas", wtype = "feet", voc = "SDPK", level = 1, price = 303, armor = 1 },
	{ id = 3556, name = "crocodile boots", kind = "botas", wtype = "feet", voc = "SDPK", level = 1, price = 3000, armor = 1 },
	{ id = 3550, name = "patched boots", kind = "botas", wtype = "feet", voc = "SDPK", level = 25, price = 6000, armor = 2 },
	{ id = 7457, name = "fur boots", kind = "botas", wtype = "feet", voc = "SDPK", level = 25, price = 6000, armor = 2 },
	{ id = 3554, name = "steel boots", kind = "botas", wtype = "feet", voc = "SDPK", level = 50, price = 90000, armor = 3 },
	{ id = 10200, name = "crystal boots", kind = "botas", wtype = "feet", voc = "KP", level = 70, price = 17940, armor = 3 },
	{ id = 3555, name = "golden boots", kind = "botas", wtype = "feet", voc = "SDPK", level = 75, price = 20550, armor = 4 },
	{ id = 44636, name = "stoic iks casque", kind = "botas", wtype = "feet", voc = "P", level = 250, price = 225300, armor = 8 },
	{ id = 3558, name = "chain legs", kind = "calcas", wtype = "legs", voc = "SDPK", level = 1, price = 304, armor = 3 },
	{ id = 3401, name = "elven legs", kind = "calcas", wtype = "legs", voc = "SDPK", level = 1, price = 304, armor = 4 },
	{ id = 22087, name = "wereboar loincloth", kind = "calcas", wtype = "legs", voc = "SDPK", level = 24, price = 4500, armor = 6 },
	{ id = 21168, name = "alloy legs", kind = "calcas", wtype = "legs", voc = "SDPK", level = 60, price = 33000, armor = 6 },
	{ id = 3557, name = "plate legs", kind = "calcas", wtype = "legs", voc = "SDPK", level = 36, price = 5743, armor = 7 },
	{ id = 3398, name = "dwarven legs", kind = "calcas", wtype = "legs", voc = "SDPK", level = 36, price = 120000, armor = 7 },
	{ id = 3363, name = "dragon scale legs", kind = "calcas", wtype = "legs", voc = "SDPK", level = 72, price = 22072, armor = 10 },
	{ id = 28720, name = "falcon greaves", kind = "calcas", wtype = "legs", voc = "KP", level = 300, price = 378300, armor = 10 },
	{ id = 34092, name = "soulshanks", kind = "calcas", wtype = "legs", voc = "S", level = 400, price = 672300, armor = 10 },
	{ id = 34093, name = "soulstrider", kind = "calcas", wtype = "legs", voc = "D", level = 400, price = 672300, armor = 10 },
	{ id = 3210, name = "hat of the mad", kind = "capacete", wtype = "head", voc = "DS", level = 1, price = 303, armor = 3 },
	{ id = 3354, name = "brass helmet", kind = "capacete", wtype = "head", voc = "SDPK", level = 1, price = 303, armor = 3 },
	{ id = 7458, name = "fur cap", kind = "capacete", wtype = "head", voc = "SDPK", level = 1, price = 303, armor = 3 },
	{ id = 3351, name = "steel helmet", kind = "capacete", wtype = "head", voc = "SDPK", level = 24, price = 2373, armor = 6 },
	{ id = 3373, name = "strange helmet", kind = "capacete", wtype = "head", voc = "SDPK", level = 24, price = 2373, armor = 6 },
	{ id = 3356, name = "devil helmet", kind = "capacete", wtype = "head", voc = "SDPK", level = 36, price = 4965, armor = 7 },
	{ id = 3393, name = "amazon helmet", kind = "capacete", wtype = "head", voc = "SDPK", level = 36, price = 4965, armor = 7 },
	{ id = 3368, name = "winged helmet", kind = "capacete", wtype = "head", voc = "SDPK", level = 72, price = 18962, armor = 10 },
	{ id = 22754, name = "visage of the end days", kind = "capacete", wtype = "head", voc = "SDPK", level = 72, price = 18962, armor = 10 },
	{ id = 3230, name = "full helmet of the ancients", kind = "capacete", wtype = "head", voc = "SDPK", level = 84, price = 25701, armor = 11 },
	{ id = 3390, name = "horned helmet", kind = "capacete", wtype = "head", voc = "SDPK", level = 84, price = 25701, armor = 11 },
	{ id = 3412, name = "wooden shield", kind = "escudo", wtype = "shield", voc = "KP", level = 1, price = 304, defense = 14 },
	{ id = 11691, name = "snake god's wristguard", kind = "escudo", wtype = "shield", voc = "DS", level = 100, price = 48300, defense = 14 },
	{ id = 3426, name = "studded shield", kind = "escudo", wtype = "shield", voc = "KP", level = 1, price = 304, defense = 15 },
	{ id = 22755, name = "book of lies", kind = "escudo", wtype = "shield", voc = "DS", level = 150, price = 108300, defense = 18 },
	{ id = 3430, name = "copper shield", kind = "escudo", wtype = "shield", voc = "KP", level = 1, price = 304, defense = 19 },
	{ id = 29426, name = "brain in a jar", kind = "escudo", wtype = "shield", voc = "DS", level = 180, price = 155820, defense = 19 },
	{ id = 3441, name = "bone shield", kind = "escudo", wtype = "shield", voc = "KP", level = 1, price = 304, defense = 20 },
	{ id = 40594, name = "alchemist's notepad", kind = "escudo", wtype = "shield", voc = "S", level = 250, price = 300300, defense = 20 },
	{ id = 3431, name = "viking shield", kind = "escudo", wtype = "shield", voc = "KP", level = 12, price = 991, defense = 22 },
	{ id = 3444, name = "sentinel shield", kind = "escudo", wtype = "shield", voc = "KP", level = 12, price = 991, defense = 22 },
	{ id = 13998, name = "depth scutum", kind = "escudo", wtype = "shield", voc = "DS", level = 120, price = 108000, defense = 25 },
	{ id = 29420, name = "shoulder plate", kind = "escudo", wtype = "shield", voc = "DS", level = 180, price = 155820, defense = 26 },
	{ id = 3427, name = "rose shield", kind = "escudo", wtype = "shield", voc = "KP", level = 42, price = 8767, defense = 27 },
	{ id = 3432, name = "ancient shield", kind = "escudo", wtype = "shield", voc = "KP", level = 42, price = 8767, defense = 27 },
	{ id = 3415, name = "guardian shield", kind = "escudo", wtype = "shield", voc = "KP", level = 60, price = 17580, defense = 30 },
	{ id = 3416, name = "dragon shield", kind = "escudo", wtype = "shield", voc = "KP", level = 66, price = 21208, defense = 31 },
	{ id = 3420, name = "demon shield", kind = "escudo", wtype = "shield", voc = "KP", level = 90, price = 90000, defense = 35 },
	{ id = 14088, name = "carapace shield", kind = "escudo", wtype = "shield", voc = "KP", level = 96, price = 96000, defense = 36 },
	{ id = 11688, name = "shield of corruption", kind = "escudo", wtype = "shield", voc = "K", level = 96, price = 44536, defense = 36 },
	{ id = 3422, name = "great shield", kind = "escudo", wtype = "shield", voc = "KP", level = 108, price = 56287, defense = 38 },
	{ id = 8079, name = "icy rainbow shield", kind = "escudo", wtype = "shield", voc = "K", level = 114, price = 62680, defense = 39 },
	{ id = 3423, name = "blessed shield", kind = "escudo", wtype = "shield", voc = "KP", level = 120, price = 69420, defense = 40 },
	{ id = 21470, name = "simple arrow", kind = "municao", wtype = "ammo", voc = "P", level = 1, price = 2, attack = 20, ammo = "arrow" },
	{ id = 3448, name = "poison arrow", kind = "municao", wtype = "ammo", voc = "P", level = 1, price = 2, attack = 23, ammo = "arrow" },
	{ id = 3447, name = "arrow", kind = "municao", wtype = "ammo", voc = "P", level = 1, price = 2, attack = 25, ammo = "arrow" },
	{ id = 22119, name = "burst arrow", kind = "municao", wtype = "ammo", voc = "P", level = 6, price = 2, attack = 27, ammo = "arrow" },
	{ id = 3449, name = "burst arrow", kind = "municao", wtype = "ammo", voc = "P", level = 6, price = 15, attack = 27, ammo = "arrow" },
	{ id = 3446, name = "bolt", kind = "municao", wtype = "ammo", voc = "P", level = 15, price = 4, attack = 30, ammo = "bolt" },
	{ id = 7363, name = "piercing bolt", kind = "municao", wtype = "ammo", voc = "P", level = 30, price = 5, attack = 33, ammo = "bolt" },
	{ id = 15792, name = "crystal bolt", kind = "municao", wtype = "ammo", voc = "P", level = 33, price = 3, attack = 36, ammo = "bolt" },
	{ id = 35901, name = "diamond arrow", kind = "municao", wtype = "ammo", voc = "P", level = 36, price = 130, attack = 37, ammo = "arrow" },
	{ id = 7365, name = "onyx arrow", kind = "municao", wtype = "ammo", voc = "P", level = 40, price = 7, attack = 38, ammo = "arrow" },
	{ id = 3450, name = "power bolt", kind = "municao", wtype = "ammo", voc = "P", level = 55, price = 7, attack = 40, ammo = "bolt" },
	{ id = 16142, name = "drill bolt", kind = "municao", wtype = "ammo", voc = "P", level = 93, price = 12, attack = 56, ammo = "bolt" },
	{ id = 15793, name = "crystalline arrow", kind = "municao", wtype = "ammo", voc = "P", level = 120, price = 20, attack = 65, ammo = "arrow" },
	{ id = 16141, name = "prismatic bolt", kind = "municao", wtype = "ammo", voc = "P", level = 123, price = 20, attack = 66, ammo = "bolt" },
	{ id = 6528, name = "infernal bolt", kind = "municao", wtype = "ammo", voc = "P", level = 141, price = 13, attack = 72, ammo = "bolt" },
	{ id = 25758, name = "spectral bolt", kind = "municao", wtype = "ammo", voc = "P", level = 159, price = 7, attack = 78, ammo = "bolt" },
	{ id = 35902, name = "spectral bolt", kind = "municao", wtype = "ammo", voc = "P", level = 159, price = 70, attack = 78, ammo = "bolt" },
	{ id = 3074, name = "wand of vortex", kind = "varinha", wtype = "wand", voc = "S", level = 6, price = 516, minDmg = 8, maxDmg = 18, mana = 1 },
	{ id = 3066, name = "snakebite rod", kind = "varinha", wtype = "wand", voc = "D", level = 6, price = 516, minDmg = 8, maxDmg = 18, mana = 2 },
	{ id = 3075, name = "wand of dragonbreath", kind = "varinha", wtype = "wand", voc = "S", level = 13, price = 1314, minDmg = 13, maxDmg = 25, mana = 3 },
	{ id = 3070, name = "moonlight rod", kind = "varinha", wtype = "wand", voc = "D", level = 13, price = 1314, minDmg = 13, maxDmg = 25, mana = 3 },
	{ id = 3072, name = "wand of decay", kind = "varinha", wtype = "wand", voc = "S", level = 19, price = 5000, minDmg = 23, maxDmg = 37, mana = 5 },
	{ id = 3069, name = "necrotic rod", kind = "varinha", wtype = "wand", voc = "D", level = 19, price = 5000, minDmg = 23, maxDmg = 37, mana = 5 },
	{ id = 8093, name = "wand of draconia", kind = "varinha", wtype = "wand", voc = "S", level = 22, price = 7500, minDmg = 23, maxDmg = 37, mana = 5 },
	{ id = 8083, name = "northwind rod", kind = "varinha", wtype = "wand", voc = "D", level = 22, price = 7500, minDmg = 23, maxDmg = 37, mana = 5 },
	{ id = 3073, name = "wand of cosmic energy", kind = "varinha", wtype = "wand", voc = "S", level = 26, price = 10000, minDmg = 37, maxDmg = 53, mana = 8 },
	{ id = 3065, name = "terra rod", kind = "varinha", wtype = "wand", voc = "D", level = 26, price = 10000, minDmg = 37, maxDmg = 53, mana = 8 },
	{ id = 12603, name = "wand of dimensions", kind = "varinha", wtype = "wand", voc = "S", level = 37, price = 8514, minDmg = 44, maxDmg = 62, mana = 9 },
	{ id = 3071, name = "wand of inferno", kind = "varinha", wtype = "wand", voc = "S", level = 33, price = 15000, minDmg = 56, maxDmg = 74, mana = 8 },
	{ id = 3067, name = "hailstorm rod", kind = "varinha", wtype = "wand", voc = "D", level = 33, price = 15000, minDmg = 56, maxDmg = 74, mana = 13 },
	{ id = 8092, name = "wand of starstorm", kind = "varinha", wtype = "wand", voc = "S", level = 37, price = 18000, minDmg = 56, maxDmg = 74, mana = 13 },
	{ id = 22183, name = "ogre scepta", kind = "varinha", wtype = "wand", voc = "D", level = 37, price = 10800, minDmg = 56, maxDmg = 74, mana = 13 },
	{ id = 25700, name = "dream blossom staff", kind = "varinha", wtype = "wand", voc = "DS", level = 80, price = 38700, minDmg = 63, maxDmg = 77, mana = 18 },
	{ id = 22765, name = "Ferumbras' staff", kind = "varinha", wtype = "wand", voc = "S", level = 65, price = 25650, minDmg = 65, maxDmg = 95, mana = 17 },
	{ id = 16096, name = "wand of defiance", kind = "varinha", wtype = "wand", voc = "S", level = 65, price = 25650, minDmg = 75, maxDmg = 95, mana = 17 },
	{ id = 16115, name = "wand of everblazing", kind = "varinha", wtype = "wand", voc = "S", level = 65, price = 25650, minDmg = 75, maxDmg = 95, mana = 17 },
	{ id = 16117, name = "muck rod", kind = "varinha", wtype = "wand", voc = "D", level = 65, price = 25650, minDmg = 75, maxDmg = 95, mana = 17 },
	{ id = 16118, name = "glacial rod", kind = "varinha", wtype = "wand", voc = "D", level = 65, price = 25650, minDmg = 75, maxDmg = 95, mana = 17 },
	{ id = 25760, name = "wand of darkness", kind = "varinha", wtype = "wand", voc = "S", level = 41, price = 10386, minDmg = 80, maxDmg = 100, mana = 15 },
	{ id = 35522, name = "jungle wand", kind = "varinha", wtype = "wand", voc = "S", level = 150, price = 135300, minDmg = 80, maxDmg = 100, mana = 19 },
	{ id = 35521, name = "jungle rod", kind = "varinha", wtype = "wand", voc = "D", level = 150, price = 135300, minDmg = 80, maxDmg = 100, mana = 19 },
	{ id = 30400, name = "cobra rod", kind = "varinha", wtype = "wand", voc = "D", level = 220, price = 290700, minDmg = 70, maxDmg = 110, mana = 21 },
	{ id = 28825, name = "deepling ceremonial dagger", kind = "varinha", wtype = "wand", voc = "DS", level = 180, price = 194700, minDmg = 86, maxDmg = 98, mana = 23 },
	{ id = 22766, name = "Ferumbras' staff", kind = "varinha", wtype = "wand", voc = "S", level = 100, price = 60300, minDmg = 80, maxDmg = 110, mana = 19 },
	{ id = 27458, name = "rod of destruction", kind = "varinha", wtype = "wand", voc = "D", level = 200, price = 240300, minDmg = 80, maxDmg = 110, mana = 20 },
	{ id = 29425, name = "energized limb", kind = "varinha", wtype = "wand", voc = "DS", level = 180, price = 194700, minDmg = 88, maxDmg = 108, mana = 24 },
	{ id = 34152, name = "lion wand", kind = "varinha", wtype = "wand", voc = "S", level = 220, price = 290700, minDmg = 89, maxDmg = 109, mana = 21 },
	{ id = 28826, name = "deepling fork", kind = "varinha", wtype = "wand", voc = "DS", level = 230, price = 317700, minDmg = 80, maxDmg = 120, mana = 23 },
	{ id = 39163, name = "naga rod", kind = "varinha", wtype = "wand", voc = "D", level = 250, price = 375300, minDmg = 90, maxDmg = 110, mana = 22 },
	{ id = 39162, name = "naga wand", kind = "varinha", wtype = "wand", voc = "S", level = 250, price = 375300, minDmg = 90, maxDmg = 120, mana = 21 },
	{ id = 49528, name = "inferniarch wand", kind = "varinha", wtype = "wand", voc = "S", level = 300, price = 540300, minDmg = 95, maxDmg = 115, mana = 21 },
	{ id = 34091, name = "soulhexer", kind = "varinha", wtype = "wand", voc = "D", level = 400, price = 960300, minDmg = 98, maxDmg = 118, mana = 21 },
	{ id = 34090, name = "soultainter", kind = "varinha", wtype = "wand", voc = "S", level = 400, price = 960300, minDmg = 100, maxDmg = 120, mana = 21 },
}
